apiVersion: v1
kind: PersistentVolume
metadata:
  name: pervolebs
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ebsstocls
  awsElasticBlockStore:
    volumeID: vol-0bba90b1d51ca98d3
    fsType: ext4