---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-efs-vol-2
  annotations:
    volume.beta.kubernetes.io/storage-class: testpersistenceefs
spec:
  storageClassName: testpersistenceefs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi