### be careful the https can take upto 10 mins to load certificates
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuard
  namespace: network-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  namespace: network-system
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  namespace: network-system
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - testexternaldnseight.test.acquiaintsvc.com
    secretName: testexternaldnseight-tls
  rules:
  - host: testexternaldnseight.test.acquiaintsvc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80