---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redistwo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: redistwo
        version: 3.2.5
    spec:
      containers:
      - name: redistwo
        image: redis:3.2.5
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: my-efs-vol-1
---
apiVersion: v1
kind: Service
metadata:
  name: redistwo
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    application: redistwo